---
- name: Create subnets
  local_action:
    module: ec2_vpc_subnet
    aws_access_key: "{{ lookup('env', 'AWS_ACCESS_KEY') }}"
    aws_secret_key: "{{ lookup('env', 'AWS_SECRET_KEY') }}"
    state: present
    region: '{{ item.region }}'
    vpc_id: '{{ item.vpc_id }}'
    az: '{{ item.az }}'
    cidr: '{{ item.cidr }}'
    resource_tags:
      Name: '{{ item.Name }}'
      app_name: '{{ item.app_name }}'
      app_environment: '{{ item.app_environment }}'
      az: '{{ item.az }}'
      region: '{{ item.region }}'
  with_items: '{{ subnets }}'
